language: node_js
node_js:
  - "v12"
env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/garments_app;
before_script:
  - npm install
  - psql -c 'create database  garments_app' -U postgres
  - psql -U postgres -d garments_app -a -f sql/garment.sql
  - psql -U postgres -d garments_app -a -f sql/data.sql
services:
  - postgresql